import Head from "next/head";
import Hls from "hls.js";
import { useEffect } from "react";

export default function Home() {
  useEffect(() => {
    const video = document.getElementById("video");
    const hls = new Hls();
    hls.loadSource(
      "https://yongsoo-study.s3.ap-northeast-2.amazonaws.com/filename.m3u8"
    );
    hls.attachMedia(video);
  }, []);

  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <span className="text-2xl">tail wind css!!</span>
      <video controls id="video">
        <sourc type="application/x-mpegURL" />
      </video>
    </div>
  );
}
